### PR TITLE
This should hide the prompts

### PR DESCRIPTION
**Pull request by Cadair**

### CODE REVIEW

**Comment by nabobalis** [comment]
Looks ok, CI broke do to a differnet issue.

**Comment by Cadair** [comment]
Is there a way to test this on @wtbarnes 's PR without doing the full release cycle?

**Comment by wtbarnes** [comment]
I'll try to pull it down and test locally.

**Comment by nabobalis** [comment]
Can we make the website use master instead of the package?

**Comment by wtbarnes** [comment]
I the requirements.txt, you could pip install from GitHub instead of PyPI

**Comment by wtbarnes** [comment]
i.e. `git+git://github.com/sunpy/sunpy-sphinx-theme.git@master` instead of `sunpy-sphinx-theme`

**Comment by wtbarnes** [comment]
If you want to change the syntax highlighting colors, I'd just do it in this PR. [Here's some of the available themes](https://help.farbox.com/pygments.html)

**Comment by wtbarnes** [comment]
[More pygments theme info](http://www.sphinx-doc.org/en/master/theming.html#creating-themes)

**Pull request merged**
