### PR TITLE
Update Mobile Menu Icon Color

### PR DESCRIPTION
**Pull request by advait-zx**
## PR Description

This pull request changes the color of the mobile menu icon to improve visibility. The previous color was dark when toggled, making it hard to distinguish against certain backgrounds.
The following changes have been made:

Updated the color of the mobile menu icon to:
line 78 --pst-color-on-surface: #ffffff;
line 79 --pst-color-primary-bg: #ffffff;

### CODE REVIEW

**Comment by nabobalis** [comment]
Does this work? I think it's the same fix as the other PR that didn't work.

**Comment by advait-zx** [comment]
how to run this css file?

**Comment by advait-zx** [comment]
@nabobalis i am not getting how to run the file both method are quite complex as i am new to this.

**Comment by advait-zx** [comment]
for tox I installed it using pip and then used this command after getting inside of file loaction  "tox -e docs"
for second i am not familiar with read the docs site which was new for me

**Comment by nabobalis** [comment]
> for tox I installed it using pip and then used this command after getting inside of file loaction "tox -e docs" 

The command should be `tox -e build_docs`. Can you see what happens if you try that?

> for second i am not familiar with read the docs site which was new for me

Sure but it's a hosting platform that builds documentation, you can think of it as just a website. No one has to interact with the build process for the site.

**Comment by nabobalis** [comment]
> ok i got now whats the problem issue is with when its in light mode

Yes. If you check the original issue, I replaced the image with the highlighted problem.

**Comment by nabobalis** [comment]
Since this is a replacement for the other PR, I will close this.

**Comment by advait-zx** [comment]
Which part of code has been replaced?

**Comment by nabobalis** [comment]
I don't understand the question, can you please try to elaborate?

**Comment by advait-zx** [comment]
i mean you said you found replacement PR so i thought you got solution.

**Comment by nabobalis** [comment]
It was your other pull request no?

**Pull request closed without merging**
