### PR TITLE
Changed the color of icon

### PR DESCRIPTION
**Pull request by advait-zx**
updated version of my last pull request for this issue

### CODE REVIEW

**Comment by nabobalis** [comment]
What problem is this solving?

**Comment by advait-zx** [comment]
actually in light mode color of icon was set to deepgrey
i updated it to white

**Comment by nabobalis** [comment]
But the description in the original message talks about a new problem that isn't the icon color. Which is why I'm confused.

**Comment by advait-zx** [comment]
Original issue says 

changed the colour of header bar for light mode

**Comment by nabobalis** [comment]
Sorry, I meant your first message in this pull request

**Comment by nabobalis** [comment]
But looking at it, yes this has not worked either.

**Comment by advait-zx** [comment]
i have made changes in sunpy-sphinx-theme\src\sunpy_sphinx_theme\theme\sunpy\static\sunpy_style.css is it correct file?

**Comment by nabobalis** [comment]
Yes.

**Comment by advait-zx** [comment]
Then it should work!!?

**Comment by nabobalis** [comment]
Can you explain why you think this change would work?

**Comment by advait-zx** [comment]
If you found solution for the issue, then delete this pull request also

**Comment by nabobalis** [comment]
No solution has been created yet, so I will only close this if you want to stop working on it.

**Comment by advait-zx** [comment]
again i have made change see if it works

**Comment by nabobalis** [comment]
I don't see any changes to this pull request? Is it on a different branch?

**Comment by advait-zx** [comment]
why its getting so complicated!!!

**Comment by nabobalis** [comment]
> why its getting so complicated!!! i think i need some more experience for this kind of issue

Can you explain what happened? I can try to help but I need more information.

**Comment by advait-zx** [comment]
well i mean after editing same file for 5-6 times still issue is not solved
(sorry for late reply)

**Comment by nabobalis** [comment]
What were you changing and were you rebuilding the documentation to check it worked via tox?

**Comment by advait-zx** [comment]
i need to run tox method again

**Comment by nabobalis** [comment]
> i need to run tox method again i runed tox method it showed `embedding documentation hyperlinks... embedding documentation hyperlinks for generated\gallery... [100%] sg_execution_times.html build finished with problems, 1 warning.`

The warning is ok, we can fix that later. Only if the build errors is there a problem.

**Comment by advait-zx** [comment]
Sure...
till that time i will try if i can find solution

**Comment by nabobalis** [comment]
The problem occurs during the mobile view. I don't think there should be any changes during the large screen experience.

**Comment by advait-zx** [comment]
why cant we use basic method by linking html file and css using `link rel` and check?

**Comment by nabobalis** [comment]
> why cant we use basic method by linking html file and css using `link rel` and check?

I have no idea what `link rel` is. 

You can open the website in your browser and modify the CSS in place via the developer tools, maybe that might be easier?

**Comment by advait-zx** [comment]
i think i got solution can you just add 
button.sidebar-toggle {
```
  font-size: var(--pst-font-size-icon);
  color: #ffffff;
  margin-bottom: 0;
  background-color: inherit;
  padding: 0.5rem;
}
```
on css file add it on 200th line

**Comment by nabobalis** [comment]
That's great, can you not add to the CSS on this pull request though?

**Comment by advait-zx** [comment]
> That's great, can you not add to the CSS on this pull request though?

i made second PR for that
just check once its issue is resolved?

**Comment by nabobalis** [comment]
Then should I close this PR?

**Comment by advait-zx** [comment]
i will close it

**Pull request closed without merging**
