### PR TITLE
added style for coordinates - fixes issue 2406

### PR DESCRIPTION
**Pull request by getsanjeev**
added style for coordinates - fixes issue 2406. This works in alignment with a change in astropy.

### CODE REVIEW

**Comment by nabobalis** [comment]
Do you know if the change was made in Astropy?

**Comment by getsanjeev** [comment]
@nabobalis I checked yesterday and PR has not been  merged yet. Should I ask them on slack?

**Comment by nabobalis** [comment]
Did they comment on the PR?

**Comment by getsanjeev** [comment]
No but somebody has asked for review from maintainers.

**Comment by nabobalis** [comment]
Will reopen when astropy PR is merged.

**Comment by Cadair** [comment]
I got the astropy PR over the line. This needs reopening and the classname changing.

**Comment by nabobalis** [comment]
Well. That was a fuck up.

**Comment by Cadair** [comment]
We should turn on the scrollbar for the graph no? at the moment its just off the right of my screen?

**Comment by Cadair** [comment]
oh wait, it wont have pulled in astropy master.

**Comment by Cadair** [comment]
nvm

**Comment by nabobalis** [comment]
@Cadair could we use the website netify build system here?

**Comment by nabobalis** [comment]
I guess we dont need it then.

**Pull request merged**
