### PR TITLE
Update navbar for new SunPy Project section

### PR DESCRIPTION
**Pull request by Cadair**
This is partnered with sunpy/sunpy.org#202

### CODE REVIEW

**Comment by nabobalis** [comment]
Need to figure out how to turn off netlify

**Comment by nabobalis** [comment]
Built website is here: https://415-95890444-gh.circle-artifacts.com/0/home/circleci/project/sunpy.org/_build/html/index.html

**Comment by nabobalis** [comment]
Looks like the stuff under the sunpy project are not linked correctly or broke.

**Comment by nabobalis** [comment]
You want me to merge this and tag a release?

**Comment by Cadair** [comment]
Only slightly before merge of the website PR. :smile:

**Pull request merged**
