### PR TITLE
Update Sidebar Toggle Button Styling

### PR DESCRIPTION
**Pull request by advait-zx**
This pull request adds custom styling for the .sidebar-toggle button. The main focus is to improve the visual appearance and layout of the sidebar toggle button
```
button.sidebar-toggle {
  font-size: var(--pst-font-size-icon);
  color: #ffffff;
  margin-bottom: 0;
  background-color: inherit;
  padding: 0.5rem;
}
```

### CODE REVIEW

**Comment by nabobalis** [comment]
This doesn't seem to have worked for me either.

Can you check on your side just to make sure?

**Comment by advait-zx** [comment]
have you tried pasting this command 
```
button.sidebar-toggle {
  font-size: var(--pst-font-size-icon);
  color: #ffffff;
  margin-bottom: 0;
  background-color: inherit;
  padding: 0.5rem;
}
```
in raw css file and then run it

**Comment by nabobalis** [comment]
I have not but why would that work but not when you edited the CSS file? 

Can you provide a screenshot of the difference on your computer?

**Comment by advait-zx** [comment]
Screenshot 2024-09-23 001348

**Comment by nabobalis** [comment]
Sorry, I meant of the changes to the rendered HTML with the color change

**Comment by advait-zx** [comment]
> Sorry, I meant of the changes to the rendered HTML with the color change

i have done using inspect mode still i will provide ss 
Screenshot 2024-09-23 002013

**Comment by nabobalis** [comment]
So we just need to work out the correct CSS incantation to get that to work in the theme?

**Comment by advait-zx** [comment]
is there any file name 

### _header.scss file in any of repos

**Comment by nabobalis** [comment]
No, you have to work out the correct CSS selector such that the changes work in the sunpy CSS file. 

That header file comes from pydata theme if I recall correctly. We can't change that file

**Comment by advait-zx** [comment]
okay...
quite time consuming issue

**Comment by nabobalis** [comment]
That's unfortunately how it can go sometimes.

**Comment by nabobalis** [comment]
> okay...
> quite time consuming issue
> Screenshot 2024-09-23 004623
> pydata_sphnix_theme needs to be change i guess
> 

As I said, the fix has to be applied in the CCS file in this repo and not pydata.

**Comment by advait-zx** [comment]
i actually got `sunpy-sphinx-theme\docs\_build\html\_static\togglebutton.css`but cant find it in repositry

**Comment by nabobalis** [comment]
That is not a file that is part of the repository.

That is from the final built HTML, that can not be added.

The changes you need to make have to go into the sunpy css file.

**Comment by advait-zx** [comment]
i have created PR check if this works

**Comment by nabobalis** [comment]
The icon is still black for me.

**Comment by advait-zx** [comment]
> I will check now but I would suggest in future trying to make sure a change works for you locally when you do a clean build.
> 
> It is also possible to check docs/readthedocs.org:sunpy-sphinx-theme as well.

so for now i should focus on other issue?

**Comment by nabobalis** [comment]
> > I will check now but I would suggest in future trying to make sure a change works for you locally when you do a clean build.
> > It is also possible to check docs/readthedocs.org:sunpy-sphinx-theme as well.
> 
> so for now i should focus on other issue?

If you want to close this and try your hand at another issue, go ahead.

**Comment by advait-zx** [comment]
> > I will check now but I would suggest in future trying to make sure a change works for you locally when you do a clean build.
> > It is also possible to check docs/readthedocs.org:sunpy-sphinx-theme as well.
> 
> so for now i should focus on other issue?

And to solve this issue i will need you help for sure

**Comment by advait-zx** [comment]
> If you want to close this and try your hand at another issue, go ahead.
i will keep it open if anyone needs to try they can

**Comment by nabobalis** [comment]
Other people can't commit code to your PR, so they will have to start over if they want to tackle this issue.

So with that in mind, lets close this PR and lets try another issue.

**Pull request closed without merging**
